# vim: set ts=2 sts=2 sw=2 expandtab :
dist: xenial
sudo: required
language: bash
services:
  - docker

before_install:
  - curl -Ls -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - chmod +x docker-build

install:
  - sudo apt-get install -y python3-pip python3-setuptools
  - sudo pip3 install --upgrade pip
  - sudo pip install PyGithub
  - ./docker-build --name ${DISTRO} --config .travis.yml --install

script:
  - ./docker-build --name ${DISTRO} -vvvv --config .travis.yml --build scripts

env:
  - DISTRO="archlinux:latest"
  - DISTRO="debian:sid"
  - DISTRO="fedora:latest"
  - DISTRO="ubuntu:16.04"
  - DISTRO="ubuntu:18.04"
  - DISTRO="ubuntu:latest"

##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    - appstream-glib
    - cmake
    - docbook-utils
    - enchant
    - git
    - gnome-common
    - gnome-doc-utils
    - gtk3
    - gtkmm
    - intltool
    - libgsf
    - libxml2
    - python
    - sword
    - webkit2gtk
    # base-devel group (for AUR installs):
    - autoconf
    - automake
    - binutils
    - bison
    - fakeroot
    - file
    - findutils
    - flex
    - gawk
    - gcc
    - gettext
    - grep
    - groff
    - gzip
    - libtool
    - m4
    - make
    - pacman
    - patch
    - pkgconf
    - sed
    - sudo
    - texinfo
    - which

  debian:
    - appstream-util
    - libbiblesync-dev
    - cmake
    - g++
    - desktop-file-utils
    - fp-utils
    - gsettings-desktop-schemas-dev
    - intltool
    - itstool
    - libdbus-glib-1-dev
    - libgconf2-dev
    - libglade2-dev
    - libgsf-1-dev
    - libenchant-dev
    - libgail-3-dev
    - libgtk-3-dev
    - libsoup2.4-dev
    - libsword-dev
    - libwebkit2gtk-4.0-dev
    - libxml2-dev
    - libxml2-utils
    - make
    - python-dev
    - swig
    - uuid-dev
    - uuid-runtime
    - yelp-tools

  fedora:
    - biblesync-devel
    - cmake
    - dbus-glib-devel
    - desktop-file-utils
    - gcc-c++
    - gconfmm26-devel
    - gtk3-devel
    - gtkhtml3-devel
    - intltool
    - itstool
    - libappstream-glib-devel
    - libgsf-devel
    - libuuid-devel
    - libxml2-devel
    - make
    - sword-devel
    - webkitgtk4-devel
    - yelp
    - yelp-tools

  ubuntu:
    - appstream-util
    - cmake
    - g++
    - desktop-file-utils
    - fp-utils
    - gsettings-desktop-schemas-dev
    - intltool
    - itstool
    - libdbus-glib-1-dev
    - libenchant-dev
    - libgail-3-dev
    - libgconfmm-2.6-dev
    - libglade2-dev
    - libgsf-1-dev
    - libgtk-3-dev
    - libsword-dev
    - libwebkitgtk-3.0-dev
    - libwebkitgtk-dev
    - libwebkit2gtk-4.0-dev
    - libxml2-dev
    - libxml2-utils
    - make
    - python-dev
    - swig
    - uuid-dev
    - uuid-runtime
    - yelp-tools

variables:
  - CFLAGS="-Wall -Werror=format-security"

before_scripts:
  - |
    START_DIR="$(pwd)"
    if [ "${DISTRO_NAME}" == "archlinux" ];then
        useradd -r -m -U -G wheel -k /dev/null aur_install
        install -m600 /dev/stdin /etc/sudoers.d/70-wheel <<< '%wheel ALL=(ALL) ALL'
        install -m600 /dev/stdin /etc/sudoers.d/99-aur_install <<< 'Defaults:aur_install !authenticate'
        aur_install() {
          su -l aur_install -c "git clone https://aur.archlinux.org/$1.git"
          su -l aur_install -c "cd $1 && makepkg --noconfirm -si"
        }
        aur_install biblesync
        aur_install gconf
        aur_install gtkhtml4
    fi
    if [ "${DISTRO_NAME}" == "debian" -o "${DISTRO_NAME}" == "ubuntu" ]; then
        # build gtkhtml4 from source
        cd "${START_DIR}"
        curl -Ls -o gtkhtml-4.10.0.tar.xz https://download.gnome.org/sources/gtkhtml/4.10/gtkhtml-4.10.0.tar.xz
        curl -Ls -o enchant-2.patch "https://aur.archlinux.org/cgit/aur.git/plain/enchant-2.patch?h=gtkhtml4"
        tar xf gtkhtml-4.10.0.tar.xz
        cd gtkhtml-4.10.0
        ./configure --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib/gtkhtml4 --localstatedir=/var --disable-static
        make -j2
        make install
    fi
    if [ "${DISTRO_NAME}" == "ubuntu" ];then
        # build biblesync from source
        cd "${START_DIR}"
        curl -Ls -o biblesync-1.2.0.tar.gz https://github.com/karlkleinpaste/biblesync/archive/1.2.0.tar.gz
        tar xf biblesync-1.2.0.tar.gz
        cd biblesync-1.2.0
        mkdir -p build
        cd build
        cmake -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=/usr -DLIBDIR=/usr/lib ..
        make -j2
        make install
        # update sword from 1.7.3 to 1.8.1
        cd "${START_DIR}"
        curl -Ls -o sword-1.8.1.tar.gz https://www.crosswire.org/ftpmirror/pub/sword/source/v1.8/sword-1.8.1.tar.gz
        curl -Ls -o sword-1.8.1-cmake.diff https://src.fedoraproject.org/rpms/sword/raw/master/f/sword-1.8.1-cmake.diff
        curl -Ls -o sword-1.8.1-icu61.diff https://src.fedoraproject.org/rpms/sword/raw/master/f/sword-1.8.1-icu61.diff
        curl -Ls -o sword-1.8.1-swig.diff https://src.fedoraproject.org/rpms/sword/raw/master/f/sword-1.8.1-swig.diff
        tar xf sword-1.8.1.tar.gz
        cd sword-1.8.1
        patch -p1 -i ../sword-1.8.1-cmake.diff
        patch -p1 -i ../sword-1.8.1-icu61.diff
        patch -p1 -i ../sword-1.8.1-swig.diff
        mkdir -p build
        cd build
        cmake -DLIBSWORD_LIBRARY_TYPE="Shared" -DSYSCONF_INSTALL_DIR='/etc' -DSWORD_BUILD_TESTS="Yes" -DSWORD_BINDINGS="Python" -DCMAKE_INSTALL_PREFIX=/usr -DLIB_INSTALL_DIR=/usr/lib/x86_64-linux-gnu ..
        make -j2
        make install
    fi

build_scripts:
  - |
    mkdir -p build
    cd build
    cmake -DCMAKE_INSTALL_PREFIX=/usr -DGTKHTML=ON ..
    make -j2
