name: Release a build

"on":
  push:
    tags:
      - '*'

jobs:
  source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install build deps
        shell: bash
        run: |
          set -ex -o pipefail
          sudo apt-get install appstream-util cmake g++ desktop-file-utils \
          fp-utils gsettings-desktop-schemas-dev intltool itstool libdbus-glib-1-dev \
          libenchant-dev libgail-3-dev libglade2-dev libgsf-1-dev libgtk-3-dev \
          libsword-dev libwebkit2gtk-4.0-dev libxml2-dev libxml2-utils make \
          python-dev swig uuid-dev uuid-runtime yelp-tools xzip libbiblesync-dev
      - name: test build
        shell: bash
        run: |
          set -ex -o pipefail
          cmake -B build .
          make -C build -j4
          make -C build package_source
          make -C build package
      - name: stash tarball
        uses: actions/upload-artifact@master
        with:
          name: src
          path: build/xiphos-${{ github.ref }}.tar.gz
      - name: stash zipfile
        uses: actions/upload-artifact@master
        with:
          name: src
          path: build/xiphos-${{ github.ref }}.zip
      - name: stash deb
        uses: actions/upload-artifact@master
        with:
          name: bin
          path: build/xiphos_${{ github.ref }}-1_amd64.deb
      - name: stash data deb
        uses: actions/upload-artifact@master
        with:
          name: bin
          path: build/xiphos-data_${{ github.ref }}-1_all.deb

  build_rpm:
    needs: source
    runs-on: ubuntu-latest
    steps:
      - name: fetch source tarball
        uses: actions/download-artifact@master
        with:
          name: src
      - name: try build
        shell: bash
        run: |
          set -ex -o pipefail
          tar -xaf xiphos-${{ github.ref }}.tar.gz
          docker run -v "${GITHUB_WORKSPACE}:/workspace" -t -i fedora:31 \
          "dnf build-dep -y xiphos && cd /workspace && cmake -B build -DGTKHTML:BOOL=ON . && make -C build -j5 && make -C build package"
      - name: stash rpm
        uses: actions/upload-artifact@master
        with:
          name: bin
          path: xiphos-${{ github.ref }}/build/xiphos-${{ github.ref }}-1.fc31.x86_64.rpm

  release:
    needs: build_rpm
    runs-on: ubuntu-latest
    steps:
      - name: fetch artifacts
        uses: actions/download-artifact@master
        with:
          name: src
      - name: fetch artifacts
        uses: actions/download-artifact@master
        with:
          name: bin
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tar.gz, *.zip, *.rpm., *.deb"
          allowUpdates: true
          name: Release ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
